# Generated by Django 3.0.6 on 2020-05-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpostapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='boast_or_roast',
            field=models.BooleanField(default=False, help_text='Check to Boast'),
        ),
    ]
